// <auto-generated />
using EmailCollector.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EmailCollector.Migrations
{
    [DbContext(typeof(EmailCollectorContext))]
    partial class EmailCollectorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("EmailCollector.Models.Email", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AttachmentName")
                        .IsRequired();

                    b.Property<byte[]>("AttachmentSHA1")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<uint>("EmailUID");

                    b.Property<string>("FileSavePath");

                    b.Property<string>("FromAddress")
                        .IsRequired();

                    b.Property<string>("SenderName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Email");
                });
#pragma warning restore 612, 618
        }
    }
}
